### ISSUE TITLE
Syncing slows down a lot if one of the devices in the Syncgroup goes offline

### ISSUE THREAD

**Issue by aghassemi** [vanadium/syncslides#13]
It might be related to the blocking Mojo calls issue.

**Comment by aghassemi** [comment]
Observation: syncing becomes fast again after a while.

**Comment by aghassemi** [comment]
Observation: Dead Syncgroups from previous runs of the app also makes syncing very slow.

**Comment by asadovsky** [comment]
What do you mean by "very slow" - can you give rough numbers for what you're seeing? I'm guessing this is just that same "unresponsive peers slow down syncing problem" we've discussed in the past: as you accrue dead/unresponsive peers (across any syncgroup still in existence), that'll slow down sync significantly - approximately 2 seconds per unresponsive peer (with variance due to randomness in peer selection). I'm starting to work with Bindu and Raja on addressing this (I can explain the details if you're interested) but it's not a trivial fix - it'll probably be at least a week until we get something checked in.

**Comment by aghassemi** [comment]
As discussed, I am planning to move all dependencies to latest soon and reproduce these bugs and provide more details.

**Comment by aghassemi** [comment]
With latest code, I see up to 10 seconds of delay in syncing slide number in a three device setup when one goes offline. After a few minutes, delay goes back to normal 1-2 seconds. @asadovsky @hpucha @rdvg

**Comment by aghassemi** [comment]
Fixed by Syncbase.
